
exports.up = function(knex, Promise) {

    return createMainCharacterTable()
      .then(createStoryBeginningTable)
      .then(createStoryMiddleTable)
      .then(createHappyEndingTable)
      .then(createSadEndingTable)
};
    function createMainCharacterTable() {
      return knex.raw('CREATE TABLE main_character (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, character_name text)');
      }

    function createStoryBeginningTable() {
          return knex.raw('CREATE TABLE story_beginning_table (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, story_middle_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE;)');
     }

     function createStoryMiddleTable() {
           return knex.raw('CREATE TABLE story_middle_table (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, story_middle_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE;)');
     }

     function createHappyEndingTable() {
           return knex.raw('CREATE TABLE happy_ending_table (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, happy_ending_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE;)');
     }

     function createSadEndingTable() {
           return knex.raw('CREATE TABLE sad_ending_table (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sad_ending_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE;)');
     }


exports.down = function(knex, Promise) {
  return dropMainCharacterTable()
    .then(dropStoryBeginningTable)
    .then(dropStoryMiddleTable)
    .then(dropHappyEndingTable)
    .then(dropSadEndingTable)

};

function dropMainCharacterTable() {
  return knex.raw('DROP TABLE main_character');
  }

function dropStoryBeginningTable() {
      return knex.raw('DROP TABLE story_beginning_table');
 }

 function dropStoryMiddleTable() {
       return knex.raw('DROP TABLE story_middle_table');
 }

 function dropHappyEndingTable() {
       return knex.raw('DROP TABLE happy_ending_table');
 }

 function dropSadEndingTable() {
       return knex.raw('DROP TABLE sad_ending_table');
 }
