exports.up = function(knex, Promise) {

    return createMainCharacterTable()
      .then(createHappyStoryTable)
      .then(createSadStoryTable)


    function createMainCharacterTable() {
      return knex.raw('CREATE TABLE main_character (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, character_name text)');
      }

     function createHappyStoryTable() {
           return knex.raw('CREATE TABLE happy_story (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, happy_story text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }

     function createSadEndingTable() {
           return knex.raw('CREATE TABLE sad_story (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sad_story text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }
};

exports.down = function(knex, Promise) {
    return dropHappyStoryTable()
    .then(dropSadStoryTable)
    .then(dropMainCharacterTable)

function dropMainCharacterTable() {
  return knex.schema.dropTable('main_character');
  }

function dropHappyStoryTable() {
      return knex.schema.dropTable('happy_story');
 }

 function dropSadStoryTable() {
       return knex.schema.dropTable('sad_story');
 }
};
