exports.up = function(knex, Promise) {

    return createMainCharacterTable()
      .then(createStoryBeginningTable)
      .then(createStoryMiddleTable)
      .then(createHappyEndingTable)
      .then(createSadEndingTable)

    function createMainCharacterTable() {
      return knex.raw('CREATE TABLE main_character (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, character_name text)');
      }

    function createStoryBeginningTable() {
          return knex.raw('CREATE TABLE story_beginning (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, story_beginning_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }

     function createStoryMiddleTable() {
           return knex.raw('CREATE TABLE story_middle (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, story_middle_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }

     function createHappyEndingTable() {
           return knex.raw('CREATE TABLE happy_ending (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, happy_ending_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }

     function createSadEndingTable() {
           return knex.raw('CREATE TABLE sad_ending (id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, sad_ending_snippet text, char_id int REFERENCES main_character(id) ON DELETE CASCADE)');
     }
};


exports.down = function(knex, Promise) {
    return dropStoryBeginningTable()
    .then(dropStoryMiddleTable)
    .then(dropHappyEndingTable)
    .then(dropSadEndingTable)
    .then(dropMainCharacterTable)

function dropMainCharacterTable() {
  return knex.schema.dropTable('main_character');
  }

function dropStoryBeginningTable() {
      return knex.schema.dropTable('story_beginning');
 }

 function dropStoryMiddleTable() {
       return knex.schema.dropTable('story_middle');
 }

 function dropHappyEndingTable() {
       return knex.schema.dropTable('happy_ending');
 }

 function dropSadEndingTable() {
       return knex.schema.dropTable('sad_ending');
 }
};
